In [62]:
import math
angle_in_radians = math.pi/4 # 45 градусов
angle_in_radians

0.7853981633974483

In [63]:
angle_in_degrees = angle_in_radians * 180 / math.pi # из радианов в градусы
angle_in_degrees 

45.0

In [64]:
angle_to_radians = angle_in_degrees * math.pi / 180 # из градусов в радианы
angle_to_radians 

0.7853981633974483

In [65]:
import numpy as np
first_array = np.array([10, 20, 30, 40]) # массив numpy
first_array 

array([10, 20, 30, 40])

In [66]:
second_array = np.arange(4) # массив numpy с помощью arange
second_array 

array([0, 1, 2, 3])

In [67]:
array_of_zeros = np.zeros(4) # массив из нулей numpy
array_of_zeros 

array([0., 0., 0., 0.])

In [68]:
array_of_ones = np.ones(4) # массив из единиц numpy
array_of_ones 

array([1., 1., 1., 1.])

In [69]:
shape_array = np.ones((3, 1)) # вывод формы массива
np.shape(shape_array) 

(3, 1)

In [70]:
first_array.dtype # вывод типа данных массива

dtype('int64')

In [71]:
second_element = first_array[1] # получение элемента по индексу
second_element

np.int64(20)

In [72]:
slice_of_array = first_array[0:3:2] # срез с первого по четвёртый элемент с шагом 2
slice_of_array

array([10, 30])

In [73]:
sum_of_array = first_array + second_array # поэлементное сложение массивов
sum_of_array 

array([10, 21, 32, 43])

In [74]:
multiplication_of_array = first_array * second_array # поэлементное умножение массивов
multiplication_of_array

array([  0,  20,  60, 120])

In [75]:
mean_value = np.mean(first_array) # вычисление среднего значение массива
mean_value

np.float64(25.0)

In [76]:
array = np.array([10, 20, 30, 40, 100])
median_value = np.median(array) # вычисление медианного значение массива
np.median(array)

np.float64(30.0)